version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./dev/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
  web:
    build: .
    env_file:
      - dev.env
    volumes:
      - .:/home/image_manager/
    ports:
      - "8000:8000"
    depends_on:
      - db